# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"FE": "FE.ipynb"}

modules = ["FE.py"]

doc_url = "https://jobindj.github.io/framework/"

git_url = "https://github.com/jobindj/framework/tree/{branch}/"

def custom_doc_links(name): return None
